EXTENSION = cdb_geocoder_admin1
DATA = cdb_geocoder_admin1--0.0.1.sql
REGRESS = cdb_geocoder_admin1_test

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
