EXTENSION = cdb_geocoder_ipaddr
DATA = cdb_geocoder_ipaddr--0.0.1.sql
REGRESS = cdb_geocoder_ipaddr_test

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
