EXTENSION = cdb_geocoder_namedplaces
DATA = cdb_geocoder_namedplaces--0.0.1.sql
REGRESS = cdb_geocoder_namedplaces_test

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
