EXTENSION = cdb_geocoder_postalcode
DATA = cdb_geocoder_postalcode--0.0.1.sql
REGRESS = cdb_geocoder_postalcode_test

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
