name: data-services PR testing
on: push
jobs:
  data-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [10, 12]
    env:
        PG_VERSION: ${{ matrix.pg_version }}

    steps:
      - uses: actions/checkout@v1

      - name: Setup gcloud authentication
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS }}

      - name: Pull base image
        run: gcloud auth configure-docker && docker pull gcr.io/cartodb-on-gcp-ci-testing/cartodb-postgresql-base:${{ matrix.pg_version }}

      - name: Checkout ci tools repository
        uses: actions/checkout@v2
        with:
          repository: CartoDB/ci-tools
          path: ci-tools
          token: ${{ secrets.CARTOFANTE_PAT }}

      - name: Copy ci files to root
        run: cp ci-tools/repos/${{ github.event.repository.name }}/* .

      - name: Start docker-compose services
        run: docker-compose -f docker-compose.yaml up -d

      - name: Run tests
        run: docker-compose -f docker-compose.yaml exec -T postgres-server bash -c "cd /data-services/geocoder/extension && make clean all install installcheck"
        timeout-minutes: 5
